# Generated by Django 2.2.2 on 2020-11-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuchyRestApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user_fk',
            new_name='user',
        ),
    ]
