# Generated by Django 3.1.1 on 2020-09-24 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fuchyRestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dateEnd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='employerPhoneNumber',
            field=models.CharField(default=9999999, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.CharField(default='test1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='paymentType',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
